### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by XxGoliathusxX** [channguyen/range-slider-view#4]
When I set the rangeCount programmatically and the value is > 5 I get ths error

```

 java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
            at com.github.channguyen.rsv.RangeSliderView.preComputeDrawingPosition(RangeSliderView.java:259)
            at com.github.channguyen.rsv.RangeSliderView.access$100(RangeSliderView.java:19)
            at com.github.channguyen.rsv.RangeSliderView$1.onPreDraw(RangeSliderView.java:150)
            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2037)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1103)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6057)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5431)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by lariosv** [comment]
I have the same problem

**Comment by amiralichesser3** [comment]
yep, same
